### ISSUE TITLE
ขยันเกินไปครับ หมั่นไส้ 555555

### ISSUE THREAD

**Issue by biigpongsatorn** [TonPC64/vue-cli-locale-th#2]

**Comment by TonPC64** [comment]
ใจเย็นนะพี่ พอดีเห็น kazupon เค้าทำเลยอยากทำบ้าง
https://github.com/vuejs-jp/vue-cli-locale-ja

**Comment by biigpongsatorn** [comment]
เหยดดด มันคือ localize หลัก ๆ หรอ

**Comment by TonPC64** [comment]
อาจจะใช่มั้งครับ ยังไม่รู้ว่าจะเอาไปใช้ตรงไหนเลย

**Comment by biigpongsatorn** [comment]
อ่อ โอเค ๆ
